
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN P5 [get_ports rst]
set_property PACKAGE_PIN P17 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports page1_btn]
set_property IOSTANDARD LVCMOS33 [get_ports page4_btn]

set_property IOSTANDARD LVCMOS33 [get_ports up_btn]
set_property IOSTANDARD LVCMOS33 [get_ports left_btn]
set_property IOSTANDARD LVCMOS33 [get_ports middle_btn]
set_property IOSTANDARD LVCMOS33 [get_ports right_btn]
set_property IOSTANDARD LVCMOS33 [get_ports down_btn]

set_property PACKAGE_PIN R2 [get_ports page1_btn]
set_property PACKAGE_PIN R1 [get_ports page4_btn]
set_property PACKAGE_PIN R15 [get_ports middle_btn]
set_property PACKAGE_PIN V1 [get_ports left_btn]
set_property PACKAGE_PIN R11 [get_ports right_btn]
set_property PACKAGE_PIN U4 [get_ports up_btn]
set_property PACKAGE_PIN R17 [get_ports down_btn]

set_property IOSTANDARD LVCMOS33 [get_ports machine_state]
set_property PACKAGE_PIN K1 [get_ports machine_state]

set_property IOSTANDARD LVCMOS33 [get_ports {tube_sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digit1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digit2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit2[0]}]

set_property PACKAGE_PIN G6 [get_ports {tube_sel[0]}]
set_property PACKAGE_PIN E1 [get_ports {tube_sel[1]}]
set_property PACKAGE_PIN F1 [get_ports {tube_sel[2]}]
set_property PACKAGE_PIN G1 [get_ports {tube_sel[3]}]
set_property PACKAGE_PIN H1 [get_ports {tube_sel[4]}]
set_property PACKAGE_PIN C1 [get_ports {tube_sel[5]}]
set_property PACKAGE_PIN C2 [get_ports {tube_sel[6]}]
set_property PACKAGE_PIN G2 [get_ports {tube_sel[7]}]

set_property PACKAGE_PIN D4 [get_ports {digit1[7]}]
set_property PACKAGE_PIN E3 [get_ports {digit1[6]}]
set_property PACKAGE_PIN D3 [get_ports {digit1[5]}]
set_property PACKAGE_PIN F4 [get_ports {digit1[4]}]
set_property PACKAGE_PIN F3 [get_ports {digit1[3]}]
set_property PACKAGE_PIN E2 [get_ports {digit1[2]}]
set_property PACKAGE_PIN D2 [get_ports {digit1[1]}]
set_property PACKAGE_PIN H2 [get_ports {digit1[0]}]

set_property PACKAGE_PIN B4 [get_ports {digit2[7]}]
set_property PACKAGE_PIN A4 [get_ports {digit2[6]}]
set_property PACKAGE_PIN A3 [get_ports {digit2[5]}]
set_property PACKAGE_PIN B1 [get_ports {digit2[4]}]
set_property PACKAGE_PIN A1 [get_ports {digit2[3]}]
set_property PACKAGE_PIN B3 [get_ports {digit2[2]}]
set_property PACKAGE_PIN B2 [get_ports {digit2[1]}]
set_property PACKAGE_PIN D5 [get_ports {digit2[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]

set_property PACKAGE_PIN H6 [get_ports {led[0]}]
set_property PACKAGE_PIN G4 [get_ports {led[1]}]
set_property PACKAGE_PIN G3 [get_ports {led[2]}]
set_property PACKAGE_PIN J4 [get_ports {led[3]}]
set_property PACKAGE_PIN H4 [get_ports {led[4]}]


set_property IOSTANDARD LVCMOS33 [get_ports {btn_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_led[0]}]
set_property PACKAGE_PIN L1 [get_ports {btn_led[2]}]
set_property PACKAGE_PIN M1 [get_ports {btn_led[1]}]
set_property PACKAGE_PIN K3 [get_ports {btn_led[0]}]